// ═══════════════════════════════════════════════════════════════════════════
//  AUTO-GENERATED by scripts/fetch-cp-stats.mjs — do not edit by hand.
//  Regenerated automatically on every `npm run build`.
// ═══════════════════════════════════════════════════════════════════════════
export const cpLive: Record<string, { label: string; value: string }[]> = {
  "codeforces": [
    {
      "label": "Rating",
      "value": "1327"
    },
    {
      "label": "Max",
      "value": "1327"
    },
    {
      "label": "Rank",
      "value": "Pupil"
    }
  ],
  "codechef": [
    {
      "label": "Rating",
      "value": "1628"
    },
    {
      "label": "Max",
      "value": "1628"
    },
    {
      "label": "Rank",
      "value": "3★"
    }
  ],
  "leetcode": [
    {
      "label": "Solved",
      "value": "45"
    },
    {
      "label": "Easy",
      "value": "18"
    },
    {
      "label": "Medium",
      "value": "23"
    },
    {
      "label": "Hard",
      "value": "4"
    }
  ]
};
